//protobuf 版本3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: twoWay.proto

//go包名，go的空间域

package twoWay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//服务请求参数（结构体）
type TwoWayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//类型 参数名 = 参数的序号（从1开始）
	A int64 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B int64 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *TwoWayReq) Reset() {
	*x = TwoWayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twoWay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwoWayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoWayReq) ProtoMessage() {}

func (x *TwoWayReq) ProtoReflect() protoreflect.Message {
	mi := &file_twoWay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoWayReq.ProtoReflect.Descriptor instead.
func (*TwoWayReq) Descriptor() ([]byte, []int) {
	return file_twoWay_proto_rawDescGZIP(), []int{0}
}

func (x *TwoWayReq) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *TwoWayReq) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

//服务响应参数（结构体）
type TwoWayRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res int64  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TwoWayRes) Reset() {
	*x = TwoWayRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twoWay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwoWayRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoWayRes) ProtoMessage() {}

func (x *TwoWayRes) ProtoReflect() protoreflect.Message {
	mi := &file_twoWay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoWayRes.ProtoReflect.Descriptor instead.
func (*TwoWayRes) Descriptor() ([]byte, []int) {
	return file_twoWay_proto_rawDescGZIP(), []int{1}
}

func (x *TwoWayRes) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *TwoWayRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_twoWay_proto protoreflect.FileDescriptor

var file_twoWay_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x77, 0x6f, 0x57, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x74, 0x77, 0x6f, 0x57, 0x61, 0x79, 0x22, 0x27, 0x0a, 0x09, 0x54, 0x77, 0x6f, 0x57, 0x61, 0x79,
	0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01,
	0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x62, 0x22,
	0x2f, 0x0a, 0x09, 0x54, 0x77, 0x6f, 0x57, 0x61, 0x79, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x32, 0x45, 0x0a, 0x0d, 0x54, 0x77, 0x6f, 0x57, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x34, 0x0a, 0x06, 0x54, 0x77, 0x6f, 0x57, 0x61, 0x79, 0x12, 0x11, 0x2e, 0x74, 0x77,
	0x6f, 0x57, 0x61, 0x79, 0x2e, 0x54, 0x77, 0x6f, 0x57, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x74, 0x77, 0x6f, 0x57, 0x61, 0x79, 0x2e, 0x54, 0x77, 0x6f, 0x57, 0x61, 0x79, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x74, 0x77, 0x6f, 0x57,
	0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_twoWay_proto_rawDescOnce sync.Once
	file_twoWay_proto_rawDescData = file_twoWay_proto_rawDesc
)

func file_twoWay_proto_rawDescGZIP() []byte {
	file_twoWay_proto_rawDescOnce.Do(func() {
		file_twoWay_proto_rawDescData = protoimpl.X.CompressGZIP(file_twoWay_proto_rawDescData)
	})
	return file_twoWay_proto_rawDescData
}

var file_twoWay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_twoWay_proto_goTypes = []interface{}{
	(*TwoWayReq)(nil), // 0: twoWay.TwoWayReq
	(*TwoWayRes)(nil), // 1: twoWay.TwoWayRes
}
var file_twoWay_proto_depIdxs = []int32{
	0, // 0: twoWay.TwoWayService.TwoWay:input_type -> twoWay.TwoWayReq
	1, // 1: twoWay.TwoWayService.TwoWay:output_type -> twoWay.TwoWayRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_twoWay_proto_init() }
func file_twoWay_proto_init() {
	if File_twoWay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_twoWay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwoWayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twoWay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwoWayRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_twoWay_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_twoWay_proto_goTypes,
		DependencyIndexes: file_twoWay_proto_depIdxs,
		MessageInfos:      file_twoWay_proto_msgTypes,
	}.Build()
	File_twoWay_proto = out.File
	file_twoWay_proto_rawDesc = nil
	file_twoWay_proto_goTypes = nil
	file_twoWay_proto_depIdxs = nil
}
